config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :items, only: [:new, :create, :show, :destroy, :edit, :update, :purchase] do
    collection do
      get 'search'
      get ':id/purchase', to: 'items#purchase', as: 'purchase'
      post 'buy/:id', to: 'items#buy', as: 'buy'
      get  'done', to: 'items#done', as: 'done'
    end
  end
  root 'items#index'
  get 'api/items/category',to: 'items#get_category'

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
    get 'signout', to: 'users#signout'
  end

  get 'purchase', to: 'items#purchase'
  get 'mypage', to: 'users#show'

  resources :credit_cards, only: [:new, :show,:destroy] do
    member do
      post 'buy', to: 'credit_cards#buy'
    end
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :user
    validates :customer_id
    validates :card_id
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, only: [:show,:new]
  before_action :set_card, only: [:destroy, :show]

  def new
    card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params['payjp_token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp_token'],
      metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
      else
        redirect_to action: "new"
      end
    end
  end

  def show
    unless @card.blank?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      @card_num = "**** **** **** " + @card_info.last4
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2, 3)
      @card_brand = @card_info.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "MasterCard"
        @card_src = "master.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    unless @card.blank?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      unless @card.destroy
        redirect_to credit_card_path, alert: "削除できませんでした。"
      end
    end
  end

  private

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/destroy.html.haml
= render 'layouts/header'
- breadcrumb :credit_cards
= render "layouts/breadcrumb"

%main.Mypage
  .Mypage__inner
    = render 'users/mypage_side'
    .Mypage__contents
      .Main__contents
        .Contents__header
          %h2 支払い方法
        .Contents__body
          .Contents--card
            %section.Card__info
              .Card__info クレジットカードの登録を削除しました
              = link_to "マイページに戻る", mypage_path, class: "Btn"
              = link_to new_credit_card_path, class: 'Btn' do
                = icon('far', 'credit-card')
                クレジットカード新規登録
= render 'layouts/footer'

app/views/credit_cards/new.html.haml
.user__all
  .user__all__user_sign_up
    = render 'layouts/header_user'
    .contents
      %h2 支払い方法
      #Card__new.contents__main.new_credit_cards
        .contents__main__block
          .field
            カード番号
            %span.caution 必須
            #number-form.payjs-outer
            = image_tag 'icon/visa.svg', class: 'CardLogo'
            = image_tag 'icon/master.svg', class: 'CardLogo'
            = image_tag 'icon/saison.svg', class: 'CardLogo'
            = image_tag 'icon/jcb.svg', class: 'CardLogo'
            = image_tag 'icon/american_express.svg', class: 'CardLogo'
            = image_tag 'icon/dinersclub.svg', class: 'CardLogo'
            = image_tag 'icon/discover.svg', class: 'CardLogo'
          .field
            有効期限
            %span.caution 必須
            #expiry-form.payjs-outer
          .field
            セキュリティーコード
            %span.caution 必須
            #cvc-form.payjs-outer
            .Text__link--right
              =link_to '#' do
                = icon('fas', 'question-circle')
                カード裏面の番号とは？
          .form-group
            #err_message
            = form_with url: pay_credit_cards_path, method: :post,id: "card_form" do |f|
              #card_token
              = f.submit "登録する", class:"Btn", id: "info_submit"
          = link_to '戻る', 'javascript:history.back()', class: 'Text__link'
    = render 'layouts/footer_user'

app/views/credit_cards/pay.html.haml
= render 'layouts/header'
- breadcrumb :credit_cards
= render "layouts/breadcrumb"

%main.Mypage
  .Mypage__inner
    = render 'users/mypage_side'
    .Mypage__contents
      .Main__contents
        .Contents__header
          %h2 支払い方法
        .Contents__body
          .Contents--card
            %section.Card__info
              %p クレジットカードの登録が完了しました
              = link_to "マイページに戻る", mypage_path, class: "Btn"
              = link_to credit_cards_path, class: 'Btn' do
                = icon('far', 'credit-card')
                登録カード一覧
= render 'layouts/footer'

app/views/credit_cards/show.html.haml
= render 'layouts/header'
- breadcrumb :credit_cards
= render "layouts/breadcrumb"

%main.Mypage
  .Mypage__inner
    = render 'users/mypage_side'
    .Mypage__contents
      .Main__contents
        .Contents__header
          %h2 支払い方法
        .Contents__body
          .Contents--card
            - if @card_info.blank?
              %section
                = link_to new_credit_card_path, class: 'Btn' do
                  = icon('far', 'credit-card')
                  クレジットカードを追加する
            - else
              .RegistCard
                = icon('fas', 'check-circle')
                .RegistCard__Info
                  %p #{@card_num}
                  %p 有効期限 #{@exp_month + " / " + @exp_year}
                  = image_tag "icon/#{@card_src}", class: "Card__brand--image", alt: @card_brand
                = link_to credit_card_path, method: :delete, class: "Btn--line Card__deleted--btn" do
                  削除する
            %section
              %p
                =link_to '#' do
                  支払い方法について
                  = icon('fas', 'chevron-right', class: "Nav__icon")
= render 'layouts/footer'