config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :items, only: [:new, :create, :show, :destroy, :edit, :update, :purchase] do
    collection do
      get 'search'
      get ':id/purchase', to: 'items#purchase', as: 'purchase'
      post 'buy/:id', to: 'items#buy', as: 'buy'
      get  'done', to: 'items#done', as: 'done'
    end
  end
  root 'items#index'
  get 'api/items/category',to: 'items#get_category'

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
    get 'signout', to: 'users#signout'
  end

  get 'purchase', to: 'items#purchase'
  get 'mypage', to: 'users#show'

  resources :credit_cards, only: [:new, :show,:destroy] do
    member do
      post 'buy', to: 'credit_cards#buy'
    end
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :item_image, dependent: :destroy
  accepts_nested_attributes_for :item_image
  belongs_to :category
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_fee_payer
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :preparation_day

  with_options presence: true do
    validates :item_image
    validates :trading_status
    validates :name
    validates :introduction
    validates :condition_id
    validates :shipping_fee_payer_id
    validates :prefecture_id
    validates :preparation_day_id
    validates :price
  end
  validates :name,length: { maximum: 40 }, allow_blank: true
  validates :introduction,length: { maximum: 1000 }, allow_blank: true
  validates :category_id, numericality:{ only_integer: true }, inclusion: { in: 1..733 }, allow_blank: true
  validates :condition_id, numericality:{ only_integer: true }, inclusion: { in: 1..6 }, allow_blank: true
  validates :shipping_fee_payer_id, numericality:{ only_integer: true }, inclusion: { in: 1..2 }, allow_blank: true
  validates :prefecture_id, numericality:{ only_integer: true }, inclusion: { in: 1..47 }, allow_blank: true
  validates :preparation_day_id, numericality:{ only_integer: true }, inclusion: { in: 1..3 }, allow_blank: true
  validates :price, numericality:{ only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }, allow_blank: true

  def self.search(search)
    if search != ""
      Item.includes(:item_image).where('name Like(?)', "%#{search}%").references(:item_image)
    else
      Item.includes(:item_image).references(:item_image)
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, only: [:new, :create, :destroy, :purchase]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :purchase, :buy]
  before_action :set_card, only: [:purchase,:buy]

  def index
    @items=Item.includes(:item_image).order("created_at DESC").limit(10)
  end

  def new
    @item = Item.new
    @item.build_item_image
    @categories = Category.roots
  end

  def get_category
    selected_category = Category.find(params[:category_id])
    @categories = selected_category.children
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      @categories = Category.roots
      render :new
    end
  end

  def edit
    unless current_user.id == @item.user_id
      redirect_to item_path(@item.id)
    else
      if @item.trading_status==1
        redirect_to item_path(@item.id)
      end
    end
  end

  def update
    @item=Item.includes(:item_image).find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      @categories = Category.roots
      redirect_to edit_item_path(@item.id)
    end
  end
  
  def destroy
    if current_user.id == @item.user_id
      @item.destroy
      redirect_to root_path
    else
      redirect_to item_path(@item)
    end
  end

  def show
    @items = Item.where(user_id: @item.user_id).where.not(id: @item.id).order("created_at DESC").limit(12)
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def purchase
    if current_user.id == @item.user_id
      redirect_to item_path(@item.id)
    else
      @address = current_user.destination
      @post_code = @address.post_code
      @full_address = @address.prefecture.name + @address.city + @address.house_number
      @user = User.find(current_user[:id])
      @user_fullname = @user.family_name + ' ' + @user.first_name
      unless @card.blank?
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @card_info = customer.cards.retrieve(@card.card_id)
        @card_num = "**** **** **** " + @card_info.last4
        @exp_month = @card_info.exp_month.to_s
        @exp_year = @card_info.exp_year.to_s.slice(2, 3)
        @card_brand = @card_info.brand
        case @card_brand
        when "Visa"
          @card_src = "visa.svg"
        when "MasterCard"
          @card_src = "master.svg"
        when "JCB"
          @card_src = "jcb.svg"
        when "American Express"
          @card_src = "american_express.svg"
        when "Diners Club"
          @card_src = "dinersclub.svg"
        when "Discover"
          @card_src = "discover.svg"
        end
      end
    end
  end

def buy
  card = CreditCard.where(user_id: current_user.id).first
  Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
  Payjp::Charge.create(
    :amount => @item.price,
    :customer => card.customer_id,
    :currency => 'jpy',
  )
  if @item.update(trading_status: 1)
    redirect_to action: :done
  end
end

def done
end

  private

  def set_item
    @item = Item.find_by_id(params[:id])
  end

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end

  def item_params
    params.require(:item).permit(:trading_status, :name, :category_id, :introduction, :condition_id, :shipping_fee_payer_id, :prefecture_id, :preparation_day_id, :price, item_image_attributes: [:id, :image_url]).merge(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/done.html.haml
= render 'layouts/header'
- breadcrumb :done
= render "layouts/breadcrumb"

%main.Mypage
  .Mypage__inner
    = render 'users/mypage_side'
    .Mypage__contents
      .Main__contents
        .Contents__header
          %h2 商品購入
        .Contents__body
          = alert
          .Contents--card
            %section.Card__info
              .Card__info
                %p
                  商品の購入が完了しました。
                  %br 発送までお待ち下さい。
              =link_to 'トップへ戻る', root_path, class: 'Btn'
              = link_to "マイページに戻る", mypage_path, class: "Btn"
= render 'layouts/footer'

app/views/items/edit.html.haml
.user__all
  = render 'layouts/header_user'

  .MainItem
    = form_with model:@item, id: 'new_item', class: 'new_item', local: true do |f|
      = render 'layouts/error_messages', model: f.object
      .Item__contents
        %label.image 出品画像
        %span.required 必須
        %p.photo １枚のみアップロードできます
        .ImageBox__Wrapper
          .Image__Wrapper
            .ImageBox__Photo
              = image_tag @item.item_image.image_url.url, alt:'Item', class:"ItemIMG"
            .ImageBox__Button
          .ImageBox__fieldE
            %label{ class: 'ImageBox__group__input__image__hidden',for:"image_1"}
              = f.fields_for :item_image, @item do |item_image| 
                = item_image.file_field :image_url, class: 'ImageBox__group__form',id:'image_1'
                .Image__box__second
                  =icon('fa', 'camera', class: 'Image__icon') 
                  %p.pic クリックしてファイルをアップロード

      %hr.Line
      .Item__contents
        .Form__group
          %label.Item__name 商品名
          %span.required 必須
          = f.text_field :name, class: "Form__inputText", placeholder: '40文字まで'
        .Form__group__second
          %label.Item__name 商品の説明
          %span.required 必須
          = f.text_area :introduction, class: "Form__inputText__second", id: "input-text", rows: "7", placeholder: "商品の説明（必須1,000文字以内）\n(色、素材、重さ、定価、注意点など）\n\n 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
        .Item__Bottom
          %span#counter 0 /1000
      %hr.Line
      .Item__contents 
        %p.box 商品の詳細
        .Item__box
          %label.section カテゴリー
          %span.required 必須
          .category__box
            = f.collection_select :category_id, Category.roots, :id, :name, {include_blank: "選択してください", selected: @item.category.root_id}, {class: "section__second item__category"}
            - unless @item.category.root_id==@item.category.parent_id
              = f.collection_select :category_id, @item.category.root.children, :id, :name, {include_blank: "選択してください", selected: @item.category.parent_id}, {class: "section__second item__category"}
            = f.collection_select :category_id, @item.category.siblings, :id, :name, {include_blank: "選択してください", selected: @item.category_id}, {class: "section__second item__category"}

        .Item__box
          %label.section 商品の状態
          %span.required 必須
          = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
      %hr.Line
      .Item__contents
        %p.box 
          配送について

          = link_to "#" do
            =icon('fa', 'question-circle', class: 'Image__Qicon')
        .Item__box
          %label.section 配送料の負担
          %span.required 必須
          = f.collection_select :shipping_fee_payer_id, ShippingFeePayer.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
        .Item__box
          %label.section 発送元の地域
          %span.required 必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
        .Item__box
          %label.section 発送までの日数
          %span.required 必須
          = f.collection_select :preparation_day_id, PreparationDay.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
      %hr.Line
      .Item__contents
        %p.box 
          価格（¥300〜9,999,999）
          = link_to "#" do
            =icon('fa', 'question-circle', class: 'Image__Qicon')
        .Price
          .Price__section
            %label.section 販売価格
            %span.required 必須
          %span.section__box ¥
          = f.text_field :price, class: "Form__input__price", placeholder: '０'
        .Price__second
          .Price__box
            販売手数料（10%）
          %span.Value1 ー
        %hr.Line
        .Price__third
          .Profit
            販売利益
          %span.Value2 ー
      .Contents__first
        .Contents__second
          = f.submit "編集する", class: "form__submit"
          = link_to "下書きに保存する", "#" , class: "Save_btn"
          = link_to "もどる", root_path , class: "Bach_btn"
      .Contents__first
        .Contents__sub
          %p
            禁止されている
            = link_to '行為', "#" , class: "law" 
            および
            = link_to '出品物', "#", class: "law"
            を必ずご確認ください。
            = link_to '偽ブランド品', "#", class: "law"
            や
            = link_to '盗難品', "#", class: "law"
            などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
            = link_to '加盟店規約', "#" , class: "law"
            に同意したことになります。

  = render 'layouts/footer_user'

app/views/items/index.html.haml
= render 'layouts/header'

.Wrapper
  %section.MainVisual
    .MainVisual__contents
      .MainVisual__title 人生を変えるフリマアプリ
      .MainVisual__text
        FURIMAはだれでもかんたんに出品・購入ができる
        %br フリマアプリです
      %ul.MainVisual__btnList
        %li
          = link_to image_tag('pict/appbtn.svg', alt:'App Store'), '#'
        %li
          = link_to image_tag('pict/googlebtn.svg', alt:'Google Play'), '#'

  %section.Feature
    .container
      %h2 FURIMAが選ばれる3つの理由
      .Feature__contents
        .Feature__box
          .Feature--image
            %span.number> 1
            =image_tag 'pict/pict-reason-01.jpg' ,alt:''
          %h3
            %span> 3分
            ですぐに出品
          .Feature--text
            スマホで入力するだけで簡単に出品できる！
        .Feature__box
          .Feature--image
            %span.number> 2
            =image_tag 'pict/pict-reason-02.jpg' ,alt:''
          %h3
            %span> シンプル
            で使いやすい
          .Feature--text
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        .Feature__box
          .Feature--image
            %span.number> 3
            =image_tag 'pict/pict-reason-03.jpg' ,alt:''
          %h3
            手数料
            %span> 業界最安
          .Feature--text
            10%でお得に出品&購入！

  %section.MiddleVisual
    .container
      .MiddleVisual__title 会員数日本一位
      .MiddleVisual__text
        FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！
        ほしかったあの商品に出会えるかもしれません
      %ul.MiddleVisual__btnList
        %li
          = link_to image_tag('pict/appbtn.svg', alt:'App Store'), '#'
        %li
          = link_to image_tag('pict/googlebtn.svg', alt:'Google Play'), '#'

  %section.Feature.Feature__second
    .container
      %h2 FURIMAの特徴
      .Feature__contents
        .Feature__box
          .Feature--image
            =image_tag 'icon/icon-01.png' ,alt:''
          %h3 簡単に売り買いできる
          .Feature--text
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        .Feature__box
          .Feature--image
            =image_tag 'icon/icon-03.png' ,alt:''
          %h3 売上金は即日振込みに対応
          .Feature--text
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        .Feature__box
          .Feature--image
            =image_tag 'icon/icon-04.png' ,alt:''
          %h3 様々な支払いに対応
          .Feature--text
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.Pickup.Pickup__category
    .container
      %h2 ピックアップカテゴリー
      .PickupBox
        %h3.Pickup__title
          = link_to '新規投稿商品', '#'
        .PickupLists
          - @items.each do |item|
            .Pickup__item
              = link_to item_path(item.id), method: :get do
                .Item__img
                  = image_tag item.item_image.image_url.url
                  - if item.trading_status == 1
                    .SoldMark
                      %span SOLD
                .Item__text
                  %h3.Item__text--name
                    =item.name
                  .Item__text--detail
                    %ul
                      %li
                        - price = item.price
                        = price.to_s(:delimited, delimiter: ',')
                        円
                      %li
                        = icon('fas', 'star', '1')
                    %p (税込)

= render 'layouts/footer'

app/views/items/new.html.haml
.user__all
  = render 'layouts/header_user'

  .MainItem
    = form_with model:@item, id: 'new_item', class: 'new_item', local: true do |f|
      = render 'layouts/error_messages', model: f.object
      .Item__contents
        %label.image 出品画像
        %span.required 必須
        %p.photo １枚のみアップロードできます
        .ImageBox__field
          %label{ class: 'ImageBox__group__input__image__hidden',for:"image_1"}
            = f.fields_for :item_image, @item.build_item_image do |item_image| 
              .image-select
                = item_image.file_field :image_url, class: 'ImageBox__group__form',id:'image_1'
              .Image__box__second
                =icon('fa', 'camera', class: 'Image__icon') 
                %p.pic クリックしてファイルをアップロード

      %hr.Line
      .Item__contents
        .Form__group
          %label.Item__name 商品名
          %span.required 必須
          = f.text_field :name, class: "Form__inputText", placeholder: '40文字まで'
        .Form__group__second
          %label.Item__name 商品の説明
          %span.required 必須
          = f.text_area :introduction, class: "Form__inputText__second", id: "input-text",rows: "7", placeholder: "商品の説明（必須1,000文字以内）\n(色、素材、重さ、定価、注意点など）\n\n 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
        .Item__Bottom
          %span#counter 0 /1000
      %hr.Line
      .Item__contents 
        %p.box 商品の詳細
        .Item__box
          %label.section カテゴリー
          %span.required 必須
          .category__box
            = f.collection_select :category_id, @categories, :id, :name, {include_blank: "選択してください"}, {class: "section__second item__category"}
        .Item__box
          %label.section 商品の状態
          %span.required 必須
          = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
      %hr.Line
      .Item__contents
        %p.box 
          配送について

          = link_to "#" do
            =icon('fa', 'question-circle', class: 'Image__Qicon')
        .Item__box
          %label.section 配送料の負担
          %span.required 必須
          = f.collection_select :shipping_fee_payer_id, ShippingFeePayer.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
        .Item__box
          %label.section 発送元の地域
          %span.required 必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
        .Item__box
          %label.section 発送までの日数
          %span.required 必須
          = f.collection_select :preparation_day_id, PreparationDay.all, :id, :name, {prompt: "選択してください"}, {class: "section__second"}
      %hr.Line
      .Item__contents
        %p.box 
          価格（¥300〜9,999,999）
          = link_to "#" do
            =icon('fa', 'question-circle', class: 'Image__Qicon')
        .Price
          .Price__section
            %label.section 販売価格
            %span.required 必須
          %span.section__box ¥
          = f.text_field :price, class: "Form__input__price", placeholder: '０'
        .Price__second
          .Price__box
            販売手数料（10%）
          %span.Value1 ー
        %hr.Line
        .Price__third
          .Profit
            販売利益
          %span.Value2 ー
      .Contents__first
        .Contents__second
          = f.submit "出品する", class: "form__submit"
          = link_to "下書きに保存する", "#" , class: "Save_btn"
          = link_to "もどる", root_path , class: "Bach_btn"
      .Contents__first
        .Contents__sub
          %p
            禁止されている
            = link_to '行為', "#" , class: "law" 
            および
            = link_to '出品物', "#", class: "law"
            を必ずご確認ください。
            = link_to '偽ブランド品', "#", class: "law"
            や
            = link_to '盗難品', "#", class: "law"
            などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
            = link_to '加盟店規約', "#" , class: "law"
            に同意したことになります。

  = render 'layouts/footer_user'

app/views/items/purchase.html.haml
.user__all
  = render 'layouts/header_user'

  .Confirmation
    .Confirmation__SubField
      %h2.Caption 購入内容の確認
    .PurchaseField
      .Information
        .Information__group
          %figure.Information__item
            = image_tag @item.item_image.image_url.url , class:"Item__Img"
        .Information__text
          %p.Information__Field= @item.name
          %p.FeePrice
            %span.FeePrice__Fee 送料込（税込）
            %span.FeePrice__Price ¥#{@item.price.to_s(:delimited)}
    .PurchaseField
      .PaymentAmount
        %span 支払金額
        %span#PaymentPrice¥#{@item.price.to_s(:delimited)}
    .PurchaseField
      .PaymentMethod
        .PaymentMethod__text
          %h3 支払い方法
          - if @card_info.blank?
            = link_to new_credit_card_path do
              = icon('fa', 'plus-circle')
              クレジットカードを登録してください
          - else
            .RegistCard
              = icon('fas', 'check-circle')
              .RegistCard__Info
                %p #{@card_num}
                %p 有効期限 #{@exp_month + " / " + @exp_year}
                = image_tag "icon/#{@card_src}", class: "Card__brand--image", alt: @card_brand
    .PurchaseField
      .Address
        .Address__Field
          %h3
            配送先
          -# リンク先変更＊サーバーサイド実装後
          = link_to '変更する>', "#" , class: "AddressChange"
        .Address__Information
          %p 〒 #{@post_code}
          %p= @full_address
          %p= @user_fullname
    .CreditCardField
      - if @card_info.blank?
        カード情報を登録して下さい。
      - else
        = link_to buy_items_path, class: 'Btn', method: :post do
          購入
  = render 'layouts/footer_user'

app/views/items/search.html.haml
= render 'layouts/header' 
- breadcrumb :search
= render "layouts/breadcrumb"

%section.Pickup.Pickup__category
  .container
    %h2 検索結果
    .PickupLists
      - @items.each do |item| 
        .Pickup__item
          = link_to item_path(item.id) do
            .Item__img
              = image_tag item.item_image.image_url.url ,width: "200px", height: "200px"
              - if item.trading_status == 1
                .SoldMark
                  %span SOLD
            .Item__text
              %h3.Item__text--name
                = item.name
              .Item__text--detail
                %ul
                  %li
                    - price = item.price
                    = price.to_s(:delimited, delimiter: ',')
                    円
                  %li
                    = icon('fas', 'star', '1')
                %p (税込)


= render 'layouts/footer'

app/views/items/show.html.haml
- provide(:title, @item.name)
= render 'layouts/header'
-# パンくずリスト：商品詳細ページ
- breadcrumb :item
= render "layouts/breadcrumb"

.Contents
  .Contents__Inner
    .Item
      %p.Item__Name
        =@item.name
      .Item__Images
        .Item__Images__Inner
          .Item__Image
            = image_tag @item.item_image.image_url_url, alt:'Item', class:"ItemIMG"
      .Item__Subimages
        .Item__Subimage
          = image_tag @item.item_image.image_url_url, alt:'Item', class:"ItemSubIMG"
      .Item__Price
        %span.Item__Price__Price
          ="¥#{@item.price.to_s(:delimited)}"
        .Item__PriceTax
          %span (税込)
          %span
            - if @item.shipping_fee_payer == 1
              送料込
            - else
              送料別
        .Item__Status
          - if @item.trading_status == 0
            - if user_signed_in? && current_user.id == @item.user_id
              = link_to '商品を編集する', edit_item_path(@item.id), method: :get, class:"ItemEdit"
              = link_to '商品を削除する', item_path(@item), method: :delete, class:"ItemDelete"
            - elsif user_signed_in? && current_user.id
              = link_to '購入画面へ進む', purchase_items_path, class:"ItemBuyer"
          - else
            .ItemSoldout
              売り切れました
      .Item__Title
        =@item.introduction
      .Item__Tables
        %table.Item__Table
          %tbody.Item__TableBody
            %tr
              %th 出品者
              %td
                =@item.user.nickname
            %tr
              %th カテゴリー
              %td
                =link_to "#" do
                  = @item.category.root.name
                - unless @item.category.root_id==@item.category.parent_id
                  %br
                  =link_to "#" do
                    =">#{@item.category.parent.name}"
                %br
                =link_to "#" do
                  =">#{@item.category.name}"
            %tr
              %th 商品の状態
              %td
                =@item.condition.name
            %tr
              %th 配送料の負担
              %td
                =@item.shipping_fee_payer.name
            %tr
              %th 発送元の地域
              %td
                =@item.prefecture.name
            %tr
              %th 発送日の目安
              %td
                =@item.preparation_day.name
      .OptionArea
        %ul.FavUl
          =link_to "#",class: "FavTag" do
            %li.Favolite
              = icon('fas', 'star')
              お気に入り
              %span.Counts 5
        %ul.FavUl
          =link_to "#",class: "FavTag" do
            %li.Report
              = icon('fa', 'flag')
              不適切な商品の通報

    .Comment
      %ul.CommentForm
      = form_with(url: "#", class: "Form") do |f|
        =f.text_area :hoge ,class: "CommentText"
        %p.NoticeMsg
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %br
        =button_tag type:"submit", class: "FormSendBtn" do
          = icon('fa', 'comment')
          コメントする
    .RelatedItemsUserSection
      - if @items.present?
        = link_to "#", class: "SectionTitle" do
          = @item.user.nickname
          のその他の出品
        .RelatedItemsUser
          - @items.each do |item|
            .RelatedItemUser
              = link_to item_path(item.id), method: :get, class: "Item__Wrapper" do
                .ItemImage
                  = image_tag item.item_image.image_url.url, class:"RelatedItemIMG"
                  - if item.trading_status == 1
                    .SoldMark
                      %span SOLD
                .ItemText
                  %p.Item__text--name
                    =item.name
                  .ItemPrice
                    %ul.PriceUl
                      %li.Priceli
                        - price = item.price
                        = price.to_s(:delimited, delimiter: ',')
                        円
                      %li.Priceli
                        = icon('fas', 'star', '1')
                    %p.Tax  (税込)
= render 'layouts/footer'