config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :items, only: [:new, :create, :show, :destroy, :edit, :update, :purchase] do
    collection do
      get 'search'
      get ':id/purchase', to: 'items#purchase', as: 'purchase'
      post 'buy/:id', to: 'items#buy', as: 'buy'
      get  'done', to: 'items#done', as: 'done'
    end
  end
  root 'items#index'
  get 'api/items/category',to: 'items#get_category'

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
    get 'signout', to: 'users#signout'
  end

  get 'purchase', to: 'items#purchase'
  get 'mypage', to: 'users#show'

  resources :credit_cards, only: [:new, :show,:destroy] do
    member do
      post 'buy', to: 'credit_cards#buy'
    end
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end

end

app/views/layouts/_breadcrumb.html.haml
.breadcrumbs
  = breadcrumbs separator: "#{icon 'fas','chevron-right'}", class: "breadcrumbs__top"

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %box1
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/_flash.html.haml
- flash.each do |message_type, message|
  = content_tag :div, message, class: message_type

app/views/layouts/_footer.html.haml
.AppBanner
  .AppBanner__contents
    .AppBanner__title
      だれでもかんたん、人生を変えるフリマアプリ
    .AppBanner__text
      今すぐ無料ダウンロード！
    %ul.AppBanner__btnList
      %li
        = link_to image_tag('pict/appbtn.svg', alt:'App Store'), '#'
      %li
        = link_to image_tag('pict/googlebtn.svg', alt:'Google Play'), '#'
.Footer
  .Footer__contents
    .Footer__box
      %h2.Footer__box--hed FURIMAについて
      %ul
        %li
          = link_to '会社概要（運営会社）','#'
        %li
          = link_to 'プライバシーポリシー','#'
        %li
          = link_to 'FURIMA利用規約','#'
        %li
          = link_to 'ポイントに関する特約','#'
    .Footer__box
      %h2.Footer__box--hed FURIMAを見る
      %ul
        %li
          = link_to 'カテゴリー一覧','#'
        %li
          = link_to 'ブランド一覧','#'
    .Footer__box
      %h2.Footer__box--hed ヘルプ＆ガイド
      %ul
        %li
          = link_to 'FRIMAガイド','#'
        %li
          = link_to 'FRIMAロゴ利用ガイドライン','#'
        %li
          = link_to 'お知らせ','#'
  .Footer__logo
    = link_to image_tag('logo/logo-white.png', alt:'FURIMA'), root_path
  .copy © FURIMA
.SellBtn
  = link_to new_item_path do
    = image_tag('icon/icon_camera.png', class:'NavIcon')
    %span 出品する

app/views/layouts/_footer_user.html.haml
%footer
  %ul
    %li プライバシーポリシー
    %li フリマ利用規約
    %li 特定商取引に関する表記
  %h1
    =link_to image_tag('logo/logo-gray.png',class: 'footer__user__img'), root_path
  %p.small @FURIMA

app/views/layouts/_header.html.haml
.Header
  .Header__contents
    .HeaderTop
      .Logo
        = link_to image_tag('logo/logo.png', alt:'FURIMA'), root_path
      .SearchBox
        = form_with(url: search_items_path, local: true, method: :get, class: 'Form') do |f|
          =f.text_field :keyword, placeholder: 'キーワードから探す', class: 'Form__inputText'
          %button{type: 'submit', class: 'Form__searchBtn'}
            = image_tag('icon/icon-search 1.png')
    .Navbar
      %ul.LeftNavLists
        %li.NavLists__Item
          = link_to '#' do
            = image_tag('icon/icon_category.png', class:'NavIcon')
            = 'カテゴリから探す'
        %li.NavLists__Item
          =link_to '#' do
            = image_tag('icon/icon_brand.png', class:'NavIcon')
            = 'ブランドから探す'
      - if user_signed_in?
        %ul.RightNavLists.UserNav
          %li.NavLists__Item
            = link_to '#' do
              = icon('fas', 'question-circle', class: 'NavIcon')
              = 'お気に入り一覧'
          %li.NavLists__Item
            = link_to '#' do
              = icon('fas', 'question-circle', class: 'NavIcon')
              = 'お知らせ'
            .NavContents
              = render 'users/info'
          %li.NavLists__Item
            = link_to '#' do
              = icon('fas', 'question-circle', class: 'NavIcon')
              = 'やること一覧'
            .NavContents
              %ul.InfoLists
                %li.InfoLists__item.NotFound
                  現在、やることリストはありません
          %li.NavLists__Item
            =link_to mypage_path do
              = image_tag('icon/member_photo_noimage_thumb.png', class: 'NavIcon')
              = 'マイページ'
            .NavContents.User
              .User__icon
                = image_tag('icon/member_photo_noimage_thumb.png', alt:'Name')
              %h2
                = current_user.nickname
              %ul.User__rating
                %li
                  評価
                  %span 20
                %li
                  出品数
                  %span 30
      - else
        %ul.RightNavLists
          %li.NavLists__Item
            =link_to 'ログイン', new_user_session_path, class: 'Btn--line'
          %li.NavLists__Item
            =link_to '新規会員登録', new_user_registration_path, class: 'Btn'

app/views/layouts/_header_user.html.haml
%header
  %h1
    =link_to image_tag('logo/logo.png',class: "user__header__img"), root_path 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title #{page_title(yield(:title))}
    %script{src: "https://js.pay.jp/v2/pay.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield